defaults:
  - _self_

agent_0: 'mfos'
agent_1: 'mfos'
batch_size: 20
just_self_play: True
reward_discount: 0.995
max_train_timestep: 30000000
metrics_log_timestep_freq: 4000

mfos:
  hidden_size: 16
  out_channels: 16
  layers_before_gru: 1
  inner_episode_length: 20
  update_interval_iterations: 1
  lr: 0.0005
  lr_final: 0.0001
  lr_decay_fraction: 1.0
  ppo_epochs: 8
  eps_clip: 0.15
  entropy_weight: 0.001
  clip_grad_norm: 0.5
