defaults:
  - _self_

agent_0: 'mfos'
agent_1: 'mfos'
batch_size: 20
just_self_play: True
reward_discount: 0.995
max_train_timestep: 30000000
metrics_log_timestep_freq: 4000

mfos:
  hidden_size: 16
  out_channels: 16
  layers_before_gru: 1
  inner_episode_length: 20
  lr: 0.001
  ppo_epochs: 12
  eps_clip: 0.2
  entropy_weight: 0.001
  clip_grad_norm: 1.0
