defaults:
  - _self_

agent_0: 'reciprocator'
agent_1: 'reciprocator'
batch_size: 20
just_self_play: True
max_train_timestep: 30000000
metrics_log_timestep_freq: 4000

reciprocator:
  reciprocal_reward_type: 'signed_petty_payoff'
  reciprocal_reward_weight: 1.0
  normalize_reciprocal_reward: True
  policy:
    hidden_size_actor: 16
    hidden_size_value: 16
    layers_before_gru_actor: 1
    layers_before_gru_value: 1
    lr: 0.005
    ppo_epochs: 5
    eps_clip: 0.15
    entropy_weight: 0.01
    clip_grad_norm: 1.0
  influence:
    hidden_size: 64
    lr: 0.01
    num_initialization_iterations: 50
    initialization_target_period: 5
    target_period: 5
    target_epochs: 5
    target_buffer_size: 8
    target_batch_size: 4096
    num_train_batches: 32
