defaults:
  - _self_

agent_0: 'reciprocator'
agent_1: 'reciprocator'
batch_size: 20
just_self_play: True
max_train_timestep: 30000000
metrics_log_timestep_freq: 4000

reciprocator:
  reciprocal_reward_type: 'petty_payoff'
  reciprocal_reward_weight: 1.0
  normalize_reciprocal_reward: False
  policy:
    model: 'conv_gru'
    hidden_size_actor: 16
    hidden_size_value: 16
    conv_out_channels: 4
    layers_before_gru_actor: 1
    layers_before_gru_value: 1
    lr: 0.005
    ppo_epochs: 40
    eps_clip: 0.15
    entropy_weight: 0.01
  influence:
    hidden_size: 32
    lr: 0.01
    num_initialization_iterations: 1
    initialization_target_period: 1
    target_period: 1
    target_epochs: 20
    target_buffer_size: 4
    target_batch_size: 4096
    num_train_batches: 64
