defaults:
  - _self_
  - hp: "test"

hp:
  seed: 45
  reward_discount: 0.96
  batch_size: 20
  train_num_iterations: 10000
  just_self_play: True
  agent_0: 'loqa'
  agent_1: 'loqa'
  eval_every: 500
  op_softmax_temp: 1.0
  game:
    height: 3
    width: 3
    gnumactions: 4
    game_length: 200
  save_dir:
    ./experiments
  save_every: 500

wandb:
  state: disabled
  project: memory_sweep
  group: coingame_selfplay
  run_name: self-play_{algorithm}_seed{seed}
  mode: online
  tags:
    - test
  wandb_dir: ./wandb
jax:
  jax_disable_jit: False
  jax_debug_nans: False
